# Generated by Django 5.2.12 on 2026-03-31 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0003_initial'),
        ('listings', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='listing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='order',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='order',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='listings.listing'),
        ),
    ]
