# Generated by Django 5.2.12 on 2026-04-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('reached', 'Reached Location'), ('picked_up', 'Picked Up'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('reached', 'Reached Location'), ('picked_up', 'Picked Up'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
